Repository codeit-sprint-fe10/Albaform, pull requests merged in 2025-01, with the labels that each got.

#45 ✨ feat: integrate form submission with api
  app/(with-main-header)/addform/_components/FormDropdown.tsx
  app/(with-main-header)/addform/_components/FormNavigator.tsx
  app/(with-main-header)/addform/_components/FormTabs.tsx
  app/(with-main-header)/addform/_components/RecruitmentDetails.tsx
  app/(with-main-header)/addform/_components/RecruitmentRequirements.tsx
  app/(with-main-header)/addform/_components/StepContent.tsx
  app/(with-main-header)/addform/_components/WorkingConditions.tsx
  app/(with-main-header)/addform/_components/WritingChip.tsx
  app/(with-main-header)/addform/_components/input/DropdownInput.tsx
  app/(with-main-header)/addform/_components/input/FileInput.tsx
  app/(with-main-header)/addform/_components/input/LocationInput.tsx
  app/(with-main-header)/addform/page.tsx
  components/DateRangePicker.tsx
  constants/form.ts
  hooks/useTemporarySave.ts
  services/form.ts
  tailwind.config.ts
  types/form.ts
Labels: ✨ feat

#51 ✨ feat: alba apply detail
  app/(with-main-header)/addform/_components/FormNavigator.tsx
  app/(with-main-header)/addform/_components/RecruitmentDetails.tsx
  app/(with-main-header)/addform/_components/RecruitmentRequirements.tsx
  app/(with-main-header)/addform/_components/StepContent.tsx
  app/(with-main-header)/addform/_components/WorkingConditions.tsx
  app/(with-main-header)/alba/[formId]/_components/Applications.tsx
  app/(with-main-header)/alba/[formId]/_components/OwnerSection.tsx
  app/(with-main-header)/alba/[formId]/_components/SummarySection.tsx
  app/(with-main-header)/alba/[formId]/page.tsx
  app/(with-main-header)/applications/[formId]/[applicationId]/page.tsx
  app/(with-main-header)/myapply/[formId]/_components/applicant/ApplicationDetail.tsx
  app/(with-main-header)/myapply/[formId]/_components/applicant/ApplicationStatusSection.tsx
  app/(with-main-header)/myapply/[formId]/_components/owner/ApplicationDetail.tsx
  app/(with-main-header)/myapply/[formId]/_components/owner/ApplicationStatusSection.tsx
  app/(with-main-header)/myapply/[formId]/_hooks/useGetApplication.tsx
  app/(with-main-header)/myapply/[formId]/_hooks/useGetMyApplication.tsx
  app/(with-main-header)/myapply/[formId]/page.tsx
  app/layout.tsx
  components/DateRangePicker.tsx
  hooks/useTemporarySave.ts
  package-lock.json
  package.json
  public/icons/download.svg
  services/alba.ts
  services/application.ts
  services/form.ts
  services/resumeFile.ts
  types/alba.ts
  types/form.ts
  utils/dateFormatter.ts
Labels: ✨ feat

#52 ✨ feat: add alba list page
  app/(with-auth-header)/_components/FormField.tsx
  app/(with-auth-header)/_components/LocationInput.tsx
  app/(with-auth-header)/_components/VisibilityInput.tsx
  app/(with-auth-header)/signup/[userRole]/_components/InformationFormSection.tsx
  app/(with-auth-header)/signup/[userRole]/layout.tsx
  app/(with-main-header)/albalist/_components/AlbaFilterSection.tsx
  app/(with-main-header)/albalist/_components/AlbaListSection.tsx
  app/(with-main-header)/albalist/_components/WriteFAB.tsx
  app/(with-main-header)/albalist/_components/filter/Dropdown.tsx
  app/(with-main-header)/albalist/_components/filter/MenuDropdown.tsx
  app/(with-main-header)/albalist/_components/filter/SearchInput.tsx
  app/(with-main-header)/albalist/_components/list/AlbaCard.tsx
  app/(with-main-header)/albalist/_components/list/AlbaCardSkeleton.tsx
  app/(with-main-header)/albalist/_components/list/AlbaListEmpty.tsx
  app/(with-main-header)/albalist/_components/list/PrivateAlbaCard.tsx
  app/(with-main-header)/albalist/page.tsx
  constants/dropdown.ts
  constants/form.ts
  public/icons/chevron-down.svg
  public/icons/empty-form.svg
  public/icons/pin-solid.svg
  public/icons/plus.svg
  public/icons/private.svg
  services/alba.ts
  types/alba.ts
Labels: ✨ feat

#55 ✨ feat: implement landing page
  app/page.tsx
  components/AnimatedItem.tsx
  public/images/landing-card-0101.png
  public/images/landing-card-0102.png
  public/images/landing-card-0201.png
  public/images/landing-card-0202.png
  public/images/landing-card-0301.png
  public/images/landing-card-0302.png
  public/images/landing-card-0401.png
  public/images/landing-card-0402.png
  public/images/landing-main.png
  tailwind.config.ts
Labels: ✨ feat

#60 ✨ feat: integrate myalbaform api
  app/(with-main-header)/addform/_components/FormDropdown.tsx
  app/(with-main-header)/myalbaform/_components/Card.tsx
  app/(with-main-header)/myalbaform/_components/EmptyAlba.tsx
  app/(with-main-header)/myalbaform/_components/MenuDropdown.tsx
  app/(with-main-header)/myalbaform/_components/MyAlbas.tsx
  app/(with-main-header)/myalbaform/_components/WriteButton.tsx
  app/(with-main-header)/myalbaform/_hooks/useGetMyCreatedAlbas.tsx
  app/(with-main-header)/myalbaform/page.tsx
  services/alba.ts
  types/alba.ts
Labels: ✨ feat

#61 53 alba detail modal
  app/(with-main-header)/alba/[formId]/_components/ApplicationActions.tsx
  app/(with-main-header)/alba/[formId]/_components/CheckMyApplicationModal.tsx
  app/(with-main-header)/alba/[formId]/_components/RecruitmentClosedModal.tsx
  app/(with-main-header)/alba/[formId]/page.tsx
  app/(with-main-header)/applications/[formId]/[applicationId]/_components/ApplicationDetail.tsx
  app/(with-main-header)/applications/[formId]/[applicationId]/_components/ApplicationStatusSection.tsx
  app/(with-main-header)/applications/[formId]/[applicationId]/page.tsx
  app/(with-main-header)/myapply/[formId]/_components/ApplicationDetail.tsx
  app/(with-main-header)/myapply/[formId]/_components/ApplicationStatusSection.tsx
  app/(with-main-header)/myapply/[formId]/page.tsx
  components/Modal.tsx
  hooks/useModal.ts
  public/icons/recruitment-closed.svg
  public/icons/x-thin.svg
  tailwind.config.ts
  types/useModal.ts
  utils/date.ts
Labels: ✨ feat

#67 ✨ feat: implement myalbafrom page
  app/(with-main-header)/addform/_components/input/LocationInput.tsx
  app/(with-main-header)/addform/page.tsx
  app/(with-main-header)/layout.tsx
  app/(with-main-header)/myalbaform/_components/Dropdown.tsx
  app/(with-main-header)/myalbaform/_components/EmptyAlba.tsx
  app/(with-main-header)/myalbaform/_components/MyAlbas.tsx
  app/(with-main-header)/myalbaform/_components/SearchBar.tsx
  app/(with-main-header)/myalbaform/_components/SearchFilters.tsx
  app/(with-main-header)/myalbaform/page.tsx
  store/myalbaform.ts
Labels: ✨ feat

#62 ✨ feat: add alba apply page
  app/(with-main-header)/addform/_components/FormNavigator.tsx
  app/(with-main-header)/addform/_components/input/FileInput.tsx
  app/(with-main-header)/addtalk/_components/FileInput.tsx
  app/(with-main-header)/apply/[formId]/_components/ApplyForm.tsx
  app/(with-main-header)/apply/[formId]/_components/Loader.tsx
  app/(with-main-header)/apply/[formId]/_components/input/FormField.tsx
  app/(with-main-header)/apply/[formId]/_components/input/ResumeInput.tsx
  app/(with-main-header)/apply/[formId]/_components/input/VisibilityInput.tsx
  app/(with-main-header)/apply/[formId]/_hook/useTanstackQuery.ts
  app/(with-main-header)/apply/[formId]/layout.tsx
  app/(with-main-header)/apply/[formId]/page.tsx
  app/(with-main-header)/edittalk/[talkId]/_components/FileInput.tsx
  constants/form.ts
  hooks/useTemporarySave.ts
  public/icons/upload.svg
  services/application.ts
  services/file.ts
  types/application.ts
  types/file.ts
  types/form.ts
Labels: ✨ feat

#71 ✨ feat: implement modal
  app/(with-main-header)/alba/[formId]/_components/ApplicationActions.tsx
  app/(with-main-header)/alba/[formId]/_components/CheckMyApplicationModal.tsx
  app/(with-main-header)/alba/[formId]/_components/DeleteAlbaModal.tsx
  app/(with-main-header)/alba/[formId]/_components/FloatingActions.tsx
  app/(with-main-header)/alba/[formId]/_components/OwnerActions.tsx
  app/(with-main-header)/alba/[formId]/_components/TermsDetail.tsx
  app/(with-main-header)/alba/[formId]/_components/input/InputField.tsx
  app/(with-main-header)/alba/[formId]/_components/input/PrivateInputField.tsx
  app/(with-main-header)/alba/[formId]/page.tsx
  app/(with-main-header)/applications/[formId]/[applicationId]/_components/ApplicationStatusSection.tsx
  app/(with-main-header)/applications/[formId]/[applicationId]/_components/RadioIcon.tsx
  app/(with-main-header)/applications/[formId]/[applicationId]/_components/UpdateApplicationStatusModal.tsx
  app/(with-main-header)/applications/[formId]/[applicationId]/page.tsx
  app/(with-main-header)/myapply/[formId]/_components/ApplicationDetail.tsx
  app/(with-main-header)/myapply/[formId]/_components/ApplicationStatusSection.tsx
  app/(with-main-header)/myapply/[formId]/_hooks/useGetMyApplication.tsx
  app/(with-main-header)/myapply/[formId]/page.tsx
  components/Modal.tsx
  public/icons/calendar-clock.svg
  public/icons/delete-alba.svg
  public/icons/edit.svg
  public/icons/info.svg
  services/alba.ts
  services/application.ts
  store/guest.ts
  types/application.ts
Labels: ✨ feat

#73 ✨ feat: implement form editing
  app/(with-main-header)/addform/_components/FormNavigator.tsx
  app/(with-main-header)/addform/_components/RecruitmentRequirements.tsx
  app/(with-main-header)/addform/_components/input/DropdownInput.tsx
  app/(with-main-header)/addform/_components/input/Input.tsx
  app/(with-main-header)/alba/[formId]/edit/page.tsx
  app/(with-main-header)/myalbaform/_components/Card.tsx
  app/(with-main-header)/myalbaform/_components/MenuDropdown.tsx
  app/(with-main-header)/myalbaform/_components/MyAlbas.tsx
  components/DateRangePicker.tsx
  services/alba.ts
  utils/filter.ts
Labels: ✨ feat

#75 ✨ feat: mypage scraps
  app/(with-main-header)/mypage/_components/Dropdown.tsx
  app/(with-main-header)/mypage/_components/Empty.tsx
  app/(with-main-header)/mypage/_components/EmptyPosts.tsx
  app/(with-main-header)/mypage/_components/Tab.tsx
  app/(with-main-header)/mypage/_components/comments/MyCommentList.tsx
  app/(with-main-header)/mypage/_components/posts/AlbatalkCard.tsx
  app/(with-main-header)/mypage/_components/posts/MyPostList.tsx
  app/(with-main-header)/mypage/_components/posts/SortDropdown.tsx
  app/(with-main-header)/mypage/_components/scraps/Filters.tsx
  app/(with-main-header)/mypage/_components/scraps/MenuDropdown.tsx
  app/(with-main-header)/mypage/_components/scraps/MyScrapList.tsx
  app/(with-main-header)/mypage/_components/scraps/Private.tsx
  app/(with-main-header)/mypage/_components/scraps/ScrapCard.tsx
  app/(with-main-header)/mypage/_components/scraps/ScrapsSortDropdown.tsx
  app/(with-main-header)/mypage/_hooks/useDeleteScrap.tsx
  app/(with-main-header)/mypage/_hooks/useGetMyScraps.tsx
  app/(with-main-header)/mypage/page.tsx
  constants/dropdown.ts
  services/mypage.ts
  store/myscraps.ts
  types/mypage.ts
Labels: ✨ feat

#76 ✨ feat: share alba detail
  .github/workflows/deploy.yml
  app/(with-main-header)/alba/[formId]/_components/AlertSection.tsx
  app/(with-main-header)/alba/[formId]/_components/DeleteAlbaModal.tsx
  app/(with-main-header)/alba/[formId]/_components/FloatingActions.tsx
  app/(with-main-header)/alba/[formId]/page.tsx
  app/(with-main-header)/applications/[formId]/[applicationId]/_components/ApplicationDetail.tsx
  app/(with-main-header)/applications/[formId]/[applicationId]/_components/ApplicationStatusSection.tsx
  app/(with-main-header)/applications/[formId]/[applicationId]/_components/UpdateApplicationStatusModal.tsx
  app/(with-main-header)/applications/[formId]/[applicationId]/page.tsx
  app/(with-main-header)/myapply/[formId]/_hooks/useGetMyApplication.tsx
  components/KakaoScript.tsx
  components/MainHeader.tsx
  components/Modal.tsx
  components/SlideMenu.tsx
  hooks/useSideMenu.ts
  public/icons/logout.svg
  public/icons/mypage.svg
  types/application.ts
Labels: ✨ feat

#77 ♻️ refactor: improve api
  app/api/auth/route.ts
  constants/api.ts
  constants/cookies.ts
  hooks/useAuth.ts
  middleware.ts
  services/axiosInstance.ts
  utils/console.ts
Labels: ♻️ refactor

#85 ✨ feat: implement draft load modal
  app/(with-main-header)/addform/_components/DraftLoadModal.tsx
  app/(with-main-header)/addform/_components/FormNavigator.tsx
  app/(with-main-header)/myalbaform/_components/CreatedCard.tsx
  app/(with-main-header)/myalbaform/_components/DeleteAlbaModal.tsx
  app/(with-main-header)/myalbaform/_components/Dropdown.tsx
  app/(with-main-header)/myalbaform/_components/MenuDropdown.tsx
  app/(with-main-header)/myalbaform/_components/MyAlbas.tsx
  app/(with-main-header)/myalbaform/_hooks/useDeleteAlba.tsx
  app/(with-main-header)/myalbaform/_hooks/useGetMyCreatedAlbas.tsx
  hooks/useDetectDevice.ts
  public/icons/draft-load.svg
Labels: ✨ feat

#91 🐛 fix: fix RSC cookie error
  app/api/auth/route.ts
  hooks/useAuth.ts
  services/axiosInstance.ts
  services/cookie.ts
Labels: 🐛 fix

#92 👷 chore: merge develop branch into main
  app/api/auth/route.ts
  hooks/useAuth.ts
  services/axiosInstance.ts
  services/cookie.ts
Labels: 👷 chore

#94 ♻️ refactor: improve image upload
  app/(with-main-header)/addform/_components/input/FileInput.tsx
  components/Loader.tsx
  hooks/usePostImage.ts
  package-lock.json
  package.json
  services/image.ts
  utils/image.ts
Labels: ♻️ refactor

#97 ♻️ refactor: refactor jsh feature
  app/(with-auth-header)/signin/[userRole]/_components/SignInFormSection.tsx
  app/(with-auth-header)/signup/[userRole]/_components/InformationFormSection.tsx
  app/(with-auth-header)/signup/[userRole]/_components/SignUpFormSection.tsx
  app/(with-main-header)/albalist/_components/AlbaListSection.tsx
  app/(with-main-header)/albalist/_components/DeleteAlbaModal.tsx
  app/(with-main-header)/albalist/_components/filter/MenuDropdown.tsx
  app/(with-main-header)/albalist/_components/list/AlbaCard.tsx
  app/(with-main-header)/apply/[formId]/_components/ApplyForm.tsx
  app/(with-main-header)/apply/[formId]/_components/ApplyLoadModal.tsx
  app/(with-main-header)/apply/[formId]/page.tsx
  app/(with-main-header)/mypage/_components/PasswordModal.tsx
  app/(with-main-header)/mypage/_components/ProfileModal.tsx
  app/(with-main-header)/mypage/_components/form/PasswordForm.tsx
  app/(with-main-header)/mypage/_components/form/ProfileForm.tsx
  components/Modal.tsx
  constants/api.ts
  store/user.ts
Labels: ♻️ refactor

#99 ♻️ refactor: improve features and UI of addform and myalbaform pages
  app/(with-main-header)/addform/_components/FormNavigator.tsx
  app/(with-main-header)/addform/_components/input/DaysInput.tsx
  app/(with-main-header)/addform/_components/input/Input.tsx
  app/(with-main-header)/addform/_components/input/Textarea.tsx
  app/(with-main-header)/addform/_hooks/usePostAlba.tsx
  app/(with-main-header)/alba/[formId]/edit/page.tsx
  app/(with-main-header)/myalbaform/_components/AppliedCard.tsx
  app/(with-main-header)/myalbaform/_components/Dropdown.tsx
  app/(with-main-header)/myalbaform/_components/MenuDropdown.tsx
  app/(with-main-header)/myalbaform/_components/MyAlbas.tsx
  app/(with-main-header)/myalbaform/_components/SearchBar.tsx
  app/(with-main-header)/myalbaform/_components/SearchFilters.tsx
  app/(with-main-header)/myalbaform/_components/WriteButton.tsx
  components/Button.tsx
  utils/filter.ts
Labels: ♻️ refactor

#102 ♻️ refactor: improve route handling
  app/(with-main-header)/alba/[formId]/edit/page.tsx
  app/(with-main-header)/albatalk/[talkId]/_hooks/useGetPostDetail.tsx
  app/(with-main-header)/albatalk/[talkId]/edit/page.tsx
  app/QueryProvider.tsx
  app/not-found.tsx
  components/MainHeader.tsx
  services/axiosInstance.ts
  tailwind.config.ts
Labels: ♻️ refactor

#104 🐛 fix: fix server cookie delete
  app/api/auth/route.ts
  hooks/useAuth.ts
  services/axiosInstance.ts
  services/cookie.ts
Labels: 🐛 fix

#106 ✨ feat: add loading component
  app/(with-main-header)/loading.tsx
  app/not-found.tsx
  app/page.tsx
  public/icons/logo.svg
Labels: ✨ feat

#107 ♻️ refactor: loading, error, toast box
  app/(with-auth-header)/signin/[userRole]/_components/SignInFormSection.tsx
  app/(with-auth-header)/signup/[userRole]/_components/InformationFormSection.tsx
  app/(with-auth-header)/signup/[userRole]/_components/SignUpFormSection.tsx
  app/(with-main-header)/alba/[formId]/_components/Applications.tsx
  app/(with-main-header)/alba/[formId]/_components/DeleteAlbaModal.tsx
  app/(with-main-header)/alba/[formId]/_components/FloatingActions.tsx
  app/(with-main-header)/alba/[formId]/_components/Location.tsx
  app/(with-main-header)/alba/[formId]/_components/OwnerSection.tsx
  app/(with-main-header)/alba/[formId]/_hooks/useGetApplications.tsx
  app/(with-main-header)/alba/[formId]/page.tsx
  app/(with-main-header)/albalist/_components/DeleteAlbaModal.tsx
  app/(with-main-header)/albalist/_components/filter/MenuDropdown.tsx
  app/(with-main-header)/albatalk/[talkId]/_components/CommentForm.tsx
  app/(with-main-header)/albatalk/[talkId]/_components/EditCommentForm.tsx
  app/(with-main-header)/albatalk/[talkId]/edit/_components/FileInput.tsx
  app/(with-main-header)/applications/[formId]/[applicationId]/_components/ApplicationDetail.tsx
  app/(with-main-header)/applications/[formId]/[applicationId]/_components/UpdateApplicationStatusModal.tsx
  app/(with-main-header)/applications/[formId]/[applicationId]/page.tsx
  app/(with-main-header)/apply/[formId]/_components/ApplyForm.tsx
  app/(with-main-header)/apply/[formId]/layout.tsx
  app/(with-main-header)/myalbaform/_components/AppliedCard.tsx
  app/(with-main-header)/myalbaform/_hooks/useDeleteAlba.tsx
  app/(with-main-header)/myapply/[formId]/_components/ApplicationDetail.tsx
  app/(with-main-header)/myapply/[formId]/page.tsx
  app/(with-main-header)/mypage/_components/form/PasswordForm.tsx
  app/(with-main-header)/mypage/_components/form/ProfileForm.tsx
  app/layout.tsx
  components/SlideMenu.tsx
  package-lock.json
  package.json
Labels: ♻️ refactor

#111 🐛 fix: validate dynamic segment to allow only numeric values
  app/(with-main-header)/alba/[formId]/edit/page.tsx
  app/(with-main-header)/alba/[formId]/page.tsx
  app/(with-main-header)/albatalk/[talkId]/edit/page.tsx
  app/(with-main-header)/albatalk/[talkId]/page.tsx
  app/(with-main-header)/myapply/[formId]/page.tsx
  app/QueryProvider.tsx
  components/WithFormIdValidation.tsx
  services/axiosInstance.ts
Labels: 🐛 fix

#112 ✨ feat: add social login
  .github/workflows/deploy.yml
  app/(with-auth-header)/_components/SocialSection.tsx
  app/(with-auth-header)/oauth/[provider]/page.tsx
  app/(with-auth-header)/oauth/signup/[userRole]/[provider]/_components/OauthSignUpFormSection.tsx
  app/(with-auth-header)/oauth/signup/[userRole]/[provider]/_components/OauthSignUpHeadSection.tsx
  app/(with-auth-header)/oauth/signup/[userRole]/[provider]/page.tsx
  app/(with-auth-header)/signin/[userRole]/page.tsx
  app/(with-auth-header)/signup/[userRole]/_components/SignUpFormSection.tsx
  app/(with-auth-header)/signup/[userRole]/_components/SocialSignUpSection.tsx
  app/(with-auth-header)/signup/[userRole]/page.tsx
  components/RoleNav.tsx
  constants/api.ts
  middleware.ts
  services/auth.ts
  types/auth.ts
Labels: ✨ feat

#115 :bug: fix: google map parse error, toast box position
  app/(with-main-header)/alba/[formId]/_components/Location.tsx
  app/layout.tsx
Labels: 🐛 fix, ♻️ refactor

#116 👷 chore: merge develop branch into main
  app/(with-main-header)/alba/[formId]/_components/Location.tsx
  app/layout.tsx
Labels: 👷 chore

#121 💄 style: improve UI/UX
  app/(with-main-header)/addform/_components/FormDropdown.tsx
  app/(with-main-header)/addform/_components/FormNavigator.tsx
  app/(with-main-header)/addform/_components/FormTabs.tsx
  app/(with-main-header)/addform/_hooks/usePostAlba.tsx
  app/(with-main-header)/albalist/_components/DeleteAlbaModal.tsx
  app/(with-main-header)/albalist/_components/filter/MenuDropdown.tsx
  app/(with-main-header)/apply/[formId]/_components/ApplyForm.tsx
  app/(with-main-header)/myalbaform/_components/AppliedCard.tsx
  app/(with-main-header)/myalbaform/_components/CreatedCard.tsx
  app/(with-main-header)/myalbaform/_components/MenuDropdown.tsx
  app/(with-main-header)/myalbaform/_components/MyAlbas.tsx
  app/(with-main-header)/mypage/_components/scraps/MenuDropdown.tsx
  app/(with-main-header)/mypage/_components/scraps/MyScrapList.tsx
  app/(with-main-header)/mypage/_components/scraps/ScrapCard.tsx
  app/(with-main-header)/mypage/_components/scraps/ScrapCardSkeleton.tsx
  app/(with-main-header)/mypage/_hooks/useDeleteScrap.tsx
  hooks/usePostImage.ts
  hooks/useTemporarySave.ts
Labels: 💄 style

#119 ✨ feat: improvement albatalk
  app/(with-main-header)/albatalk/[talkId]/_components/CommentList.tsx
  app/(with-main-header)/albatalk/_components/SearchBar.tsx
  app/(with-main-header)/albatalk/_hooks/useGetPosts.tsx
  app/(with-main-header)/albatalk/page.tsx
Labels: ✨ feat

#125 ✨ feat: add ga
  app/(with-auth-header)/layout.tsx
  app/(with-main-header)/layout.tsx
  components/GoogleAnalytics.tsx
Labels: ✨ feat

#118 🐛 fix: google map and carousel
  app/(with-main-header)/alba/[formId]/_components/ApplicationActions.tsx
  app/(with-main-header)/alba/[formId]/_components/Applications.tsx
  app/(with-main-header)/alba/[formId]/_components/Carousel.tsx
  app/(with-main-header)/alba/[formId]/_components/FloatingActions.tsx
  app/(with-main-header)/alba/[formId]/_components/GoogleMap.tsx
  app/(with-main-header)/alba/[formId]/_components/OwnerActions.tsx
  app/(with-main-header)/alba/[formId]/_components/OwnerSection.tsx
  app/(with-main-header)/alba/[formId]/_components/skeleton/ApplicationsSkeleton.tsx
  app/(with-main-header)/alba/[formId]/page.tsx
  app/(with-main-header)/applications/[formId]/[applicationId]/page.tsx
  app/(with-main-header)/myapply/[formId]/page.tsx
  components/MainHeader.tsx
  public/icons/edit.svg
Labels: 🐛 fix

#130 👷 chore: merge develop branch into main
  .github/workflows/deploy.yml
  app/(with-auth-header)/layout.tsx
  app/(with-main-header)/albatalk/_components/Pagination.tsx
  app/(with-main-header)/layout.tsx
  app/layout.tsx
Labels: 👷 chore

#131 🐛 fix: add convert to months on applications list
  app/(with-main-header)/alba/[formId]/_components/Applications.tsx
Labels: 🐛 fix

#132 👷 chore: merge develop branch into main
  app/(with-main-header)/alba/[formId]/_components/Applications.tsx
Labels: 👷 chore
